version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: compose-reco-facial
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: recofacial
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
    - "3306:3306"
    volumes:
    - db_data:/var/lib/mysql
    networks:
    - mysql_network


volumes:
  db_data:

networks:
  mysql_network: